<?php 
function get_themedetails(){
	$details = array(
					'default' => array('title' => 'default', 'description' => 'Wide Slider'),
					'style1' => array('title' => '2 Column', 'description' => '2 Column Header'),
					'style2' => array('title' => 'Full Screen', 'description' => 'Full screen'),
					'style3' => array('title' => 'Tanjung Rhu Concept', 'description' => 'Tanjung Rhu Concept'),
					'style4' => array('title' => 'Royal Chulan Concept', 'description' => 'Royal Chulan Concept'),
				);
			
	return $details;
} 

function get_default_css($themestyle){

	switch($themestyle){
		case 'style1': {
			$defaultstyle  = 'body {font-size:13px; color:#fff; font-family:sans-serif;}'."\n";
			$defaultstyle .= 'a, a:hover { color:#fff;}'."\n";
			$defaultstyle .= '#header {background:rgba(255,255,255,0.5);}'."\n";
			$defaultstyle .= '#main-container { background:#444;}'."\n";
			$defaultstyle .= '#main-menu li a { padding:5px 10px; background:#999; color:#fff;}'."\n";
			$defaultstyle .= '#main-menu li.current-menu-item a, #main-menu li a:hover { background-color:#777; color:#fff;}'."\n";		
			$defaultstyle .= '#primary-main{background:#333; padding:20px;}'."\n";
			$defaultstyle .= '#cta-container {color:#ffffff; background:#252525;}'."\n";
			$defaultstyle .= '#bpgtipcontent { background:#E0C48F; color:#000;}'."\n";
			$defaultstyle .= '#bpgtipcontent:after { border-color:#E0C48F transparent transparent transparent;}'."\n";
			$defaultstyle .= '#logo-container {padding:1em 0; text-align:center;}'."\n";
			$defaultstyle .= '#footer {color:#000;}'."\n";
			$defaultstyle .= '#footer a {color:#000;}'."\n";
			$defaultstyle .= '#teaser-container .teaser-box{display: block; position: relative;}'."\n";
			$defaultstyle .= '#teaser-container .teaser-details{position: absolute; top: 0; color: #333333; block; height: 100%; right: 20px; width:110px; text-align: center; padding: 0 10px; background: rgba(255,255,255,.70); -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#CCFFFFFF,endColorstr=#CCFFFFFF)"; filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#CCFFFFFF,endColorstr=#CCFFFFFF); zoom: 1; }'."\n";
			$defaultstyle .= '#teaser-container .teaser-details .sub-title{padding:30px 0 0; font-size: 1.1em; font-weight: bold; margin: 0; text-transform: uppercase;}';
			$defaultstyle .= '#teaser-container .tagline{display:block; padding:14px 0 0; font-weight:bold;}'."\n";
			$defaultstyle .= '#teaser-container .readmore{float:right; color: #00635A; text-decoration:underline; font-weight:bold;}'."\n";
			$defaultstyle .= '#teaser-container .teaserlink{display:block; text-align:right;}'."\n";
			return $defaultstyle;
		} break;
		case 'style2': {
			$defaultstyle  = 'html, body {display:block; position:relative; height:100%;}'."\n";
			$defaultstyle .= 'body {font-size:13px; color:#fff; font-family:sans-serif;}'."\n";
			$defaultstyle .= 'a, a:hover { color:#fff;}'."\n";
			$defaultstyle .= '#header {background:rgba(255,255,255,0.5);}'."\n";
			$defaultstyle .= '#main-container { background:#444;}'."\n";
			$defaultstyle .= '#main-menu li a { padding:5px 10px; background:#999; color:#fff;}'."\n";
			$defaultstyle .= '#main-menu li.current-menu-item a, #main-menu li a:hover { background-color:#777; color:#fff;}'."\n";		
			$defaultstyle .= '#primary-main{background:#333; padding:20px;}'."\n";
			$defaultstyle .= '#cta-container {color:#ffffff; background:#252525;}'."\n";
			$defaultstyle .= '#bpgtipcontent { background:#E0C48F; color:#000;}'."\n";
			$defaultstyle .= '#bpgtipcontent:after { border-color:#E0C48F transparent transparent transparent;}'."\n";
			$defaultstyle .= '#logo-container {padding:1em 0; text-align:center;}'."\n";
			$defaultstyle .= '#footer {color:#000;}'."\n";
			$defaultstyle .= '#footer a {color:#000;}'."\n";
			$defaultstyle .= '#teaser-container .teaser-box{display: block; position: relative;}'."\n";
			$defaultstyle .= '#teaser-container .teaser-details{position: absolute; top: 0; color: #333333; block; height: 100%; right: 20px; width:110px; text-align: center; padding: 0 10px; background: rgba(255,255,255,.70); -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#CCFFFFFF,endColorstr=#CCFFFFFF)"; filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#CCFFFFFF,endColorstr=#CCFFFFFF); zoom: 1; }'."\n";
			$defaultstyle .= '#teaser-container .teaser-details .sub-title{padding:30px 0 0; font-size: 1.1em; font-weight: bold; margin: 0; text-transform: uppercase;}';
			$defaultstyle .= '#teaser-container .tagline{display:block; padding:14px 0 0; font-weight:bold;}'."\n";
			$defaultstyle .= '#teaser-container .readmore{float:right; color: #00635A; text-decoration:underline; font-weight:bold;}'."\n";
			$defaultstyle .= '#teaser-container .teaserlink{display:block; text-align:right;}'."\n";
			return $defaultstyle;
		} break;
		case 'style3': {
			$defaultstyle  = 'body{background:#FBFBFB; font-family:sans-serif; color:#3f3f3f;}'."\n";
			$defaultstyle .= '.home #slider-container{margin-bottom:4em;}'."\n";
			$defaultstyle .= 'h1, h2, h3, .title, .sub-title{color:#3A4C02; font-weight:normal;}'."\n";
			$defaultstyle .= '.ctabutton{text-decoration:none;}'."\n";
			$defaultstyle .= '#social-container{position:absolute; top:1em; right:0;}'."\n";
			$defaultstyle .= '#header{position:absolute; top; background:rgba(255,255,255,0.6); -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#99FFFFFF,endColorstr=#99FFFFFF)"; filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#99FFFFFF,endColorstr=#99FFFFFF); zoom: 1;}'."\n";
			$defaultstyle .= '#header .content{padding:10px 0;}'."\n";
			$defaultstyle .= '#main-menu-container{display:block; position:relative; text-align:center; background:#fff;}'."\n";
			$defaultstyle .= '#main-menu > ul{text-align:center;}'."\n";
			$defaultstyle .= '#main-menu > ul li a{padding:8px 16px; color:#894E2D;}'."\n";
			$defaultstyle .= '#main-menu > ul li a:hover, #main-menu > ul li.current-menu-item a{background:#C9C9C9; color:#3A4C02; border-top:3px solid #894E2D; }'."\n";
			$defaultstyle .= '#cta-container .content{width:auto;}'."\n";
			$defaultstyle .= '#cta-container .cta-title-container{background:#843F20; position:absolute; top:-55px; display:inline-block; padding:6px 0; width:90%; margin:0 5%;}'."\n";
			$defaultstyle .= '#cta-container .cta-title-container h3{text-transform:uppercase; font-size:0.8em; font-weight:bold; color:#fff;}'."\n";
			$defaultstyle .= '#cta-container .cta-calendar-container .calendar-label{text-transform:uppercase;}'."\n";
			$defaultstyle .= '#slider-main .slider-image-caption{position:absolute; bottom:140px; height:auto; width:80%; left:10%; background:rgba(0,0,0,0.4); color:#fff; }'."\n";
			$defaultstyle .= '#carousel-content{bottom:0;}'."\n";
			$defaultstyle .= '#slider-carousel ul li span{background:#3A4C02; color:#fff; padding:4px 0;}'."\n";
			$defaultstyle .= '#slider-carousel ul li:hover span, #slider-carousel ul li.flex-active-slide span{background:#843F20;}'."\n";
			$defaultstyle .= '.teaser-box{display:block; position:relative;}'."\n";
			$defaultstyle .= '.teaser-details{position:absolute; bottom:0; left:0; width:80%; padding:6px; background:#843F20; }'."\n";
			$defaultstyle .= '.teaser-details .sub-title{color:#fff; margin:0;}'."\n";
			$defaultstyle .= '.teaser-details .teaserlink{background:#fff; height:100%; position:absolute; right:0;  width:50px; text-align:center; top:0; color:#252525; line-height:40px;}'."\n";
			$defaultstyle .= '#front-address-container{border-top:3px solid #894E2D; border-bottom:3px solid #894E2D; text-align:right; padding:1em 0;}'."\n";
			$defaultstyle .= '#main-container{margin-bottom:2em;}'."\n";
			$defaultstyle .= '#footer{background:#333333; color:#C0C0C0; padding:1.5em 0;}'."\n";
			$defaultstyle .= '#footer *{color:inherit;}'."\n";
			$defaultstyle .= '#footer h4{font-size:1.4em; margin-bottom:1em;}'."\n";
			return $defaultstyle;
		} break;
		case 'style4': {
			$defaultstyle  = '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			$defaultstyle .= '';
			return $defaultstyle;
		} break;
		default: {
			$defaultstyle  = 'body {font-size:14px; color:#fff; font-family:sans-serif;}'."\n";
			$defaultstyle .= 'a, a:hover { color:#fff;}'."\n";
			$defaultstyle .= '#header {background:rgba(255,255,255,0.5);}'."\n";
			$defaultstyle .= '#main-container { background:#444;}'."\n";
			$defaultstyle .= '#main-menu li a { padding:5px 10px; background:#999; color:#fff;}'."\n";
			$defaultstyle .= '#main-menu li.current-menu-item a, #main-menu li a:hover { background-color:#777; color:#fff;}'."\n";		
			$defaultstyle .= '#primary-main{background:#333; padding:20px;}'."\n";
			$defaultstyle .= '#cta-container {color:#ffffff; background:#252525;}'."\n";
			$defaultstyle .= '#bpgtipcontent { background:#E0C48F; color:#000;}'."\n";
			$defaultstyle .= '#bpgtipcontent:after { border-color:#E0C48F transparent transparent transparent;}'."\n";
			$defaultstyle .= '#logo-container {padding:1em}'."\n";
			$defaultstyle .= '#footer {color:#000;}'."\n";
			$defaultstyle .= '#footer a {color:#000;}'."\n";
			$defaultstyle .= '#teaser-container .teaser-box{display: block; position: relative;}'."\n";
			$defaultstyle .= '#teaser-container .teaser-details{position: absolute; top: 0; color: #333333; block; height: 100%; right: 20px; width:110px; text-align: center; padding: 0 10px; background: rgba(255,255,255,.70); -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#CCFFFFFF,endColorstr=#CCFFFFFF)"; filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#CCFFFFFF,endColorstr=#CCFFFFFF); zoom: 1; }'."\n";
			$defaultstyle .= '#teaser-container .teaser-details .sub-title{padding:30px 0 0; font-size: 1.1em; font-weight: bold; margin: 0; text-transform: uppercase;}';
			$defaultstyle .= '#teaser-container .tagline{display:block; padding:14px 0 0; font-weight:bold;}'."\n";
			$defaultstyle .= '#teaser-container .readmore{float:right; color: #00635A; text-decoration:underline; font-weight:bold;}'."\n";
			$defaultstyle .= '#teaser-container .teaserlink{display:block; text-align:right;}'."\n";
			return $defaultstyle;
		}
	} 
}

function get_mediaquery_css($themestyle){ 
	
	switch($themestyle){
		case 'style1' : {
			$mediaquerystyle  = '@media (min-width: 1367px) {'."\n";
			$mediaquerystyle .= '	.content{width:1100px;}'."\n";
			$mediaquerystyle .= '	#slider-container{max-width:1960px; margin:0 auto;}'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width:1366px) {'."\n";
			$mediaquerystyle .= '	.content{width:1100px;}'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media(max-width:1199px) {'."\n";
			$mediaquerystyle .= '	.content{width:960px;}'."\n";
			$mediaquerystyle .= '	.bpgtip{left:0;}'."\n";
			$mediaquerystyle .= '	#bpgtipcontent{top:200%; left:-15px; height:auto; min-width:200px; font-size:12px;}'."\n";
			$mediaquerystyle .= '	#bpgtipcontent:after{top:-24px; border-color: transparent transparent #E0C48F transparent; }'."\n";
			$mediaquerystyle .= '	#bpgmodal h2{font-size:1.231em;}'."\n";
			$mediaquerystyle .= '	#cta-container{width:250px; text-align:center; bottom:10%; right:10%; padding:10px;}'."\n";
			$mediaquerystyle .= '	#cta-container .content{width:auto;}'."\n";
			$mediaquerystyle .= '	#cta-container .control-wrapper{display:block; position:relative; margin-bottom:0.5em;}'."\n";
			$mediaquerystyle .= '	#cta-container .cta-moc-container{width:auto;}'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width: 979px) {'."\n";
			$mediaquerystyle .= '	body{font-size:12px;}'."\n";
			$mediaquerystyle .= '	.large, h1{font-size:1.333em; margin-bottom:1em;}'."\n";
			$mediaquerystyle .= '	.medium, h2{font-size:1.167em; margin-bottom:0.5em;}'."\n";
			$mediaquerystyle .= '	.normal, h3 {font-size:1.083em; margin-bottom:0.5em;}'."\n";	
			$mediaquerystyle .= '	.normal, h4, h5, h6{font-size:1em;}'."\n";
			$mediaquerystyle .= '	.content{width:718px;}'."\n";
			$mediaquerystyle .= '	#header .content, #footer .content{width:auto;}'."\n";
			$mediaquerystyle .= '	#logo-container{display:block; position:relative; text-align:center; width:auto; float:none;}'."\n";
			$mediaquerystyle .= '	#slider-container{min-height:0; display:block; width:auto; float:none;}'."\n";
			$mediaquerystyle .= '	#main-menu-container{position:relative; bottom:auto; right:auto;}'."\n";
			$mediaquerystyle .= '	#secondary-menu-container{float:none; margin-bottom:1em;}'."\n";
			$mediaquerystyle .= '	#secondary-menu ul{text-align:center;}'."\n";
			$mediaquerystyle .= '	#social-media-container{float:none; text-align:center;}'."\n";
			$mediaquerystyle .= '	#footer{height:auto;}'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width: 767px) {'."\n";
			$mediaquerystyle .= '	.content{width:500px;}'."\n";
			$mediaquerystyle .= '	#main-menu{background:#d6d6d6; display:block; position:relative; width:100%; margin:0 auto; bottom:0;}'."\n";
			$mediaquerystyle .= '		#main-menu ul li{display:block; position:relative; text-align:center; margin:0;}'."\n";
			$mediaquerystyle .= '	.image-container{width:300px; margin:0 auto 1em;}'."\n";
			$mediaquerystyle .= '	.visible-layer{display:none;}'."\n";
			$mediaquerystyle .= '	.hide-layer{display:block;}'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width:570px) {'."\n";
			$mediaquerystyle .= '	#cta-container{width: auto; padding:10px; position:relative; right:auto; bottom:auto;}'."\n";
			$mediaquerystyle .= '	.flex-control-nav {display:none;}'."\n";
			$mediaquerystyle .= '	.content{width:320px;}'."\n";
			$mediaquerystyle .= '	.image-container{width:auto; margin:0 auto 1em;}'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width: 480px) {'."\n";
			$mediaquerystyle .= '	.content{width:280px;}'."\n";
			$mediaquerystyle .= '}'."\n";
			return $mediaquerystyle;
		} break;
		case 'style2' : {
			$mediaquerystyle .='@media (min-width: 1367px) {'."\n";
			$mediaquerystyle .='	.content{width:1100px;}'."\n";
			$mediaquerystyle .='}'."\n";
			$mediaquerystyle .='@media (max-width:1366px) {'."\n";
			$mediaquerystyle .='	.content{width:1100px;}'."\n";
			$mediaquerystyle .='}'."\n";
			$mediaquerystyle .='@media(max-width:1199px) {'."\n";
			$mediaquerystyle .='	#wrapper{min-height:0;}'."\n";
			$mediaquerystyle .='	.content, #cta-container .cta{width:960px;}'."\n";
			$mediaquerystyle .='	#header{position:relative;}'."\n";
			$mediaquerystyle .='	#header-container .content{width:auto;}'."\n";
			$mediaquerystyle .='	#logo-container{float:none; text-align:center; display:inline-block; width:100%;}'."\n";
			$mediaquerystyle .='	#menu-cta-container{float:none; position:relative; width:auto;}'."\n";
			$mediaquerystyle .='		#main-menu ul{text-align:center;}'."\n";
			$mediaquerystyle .='	#slider-container{position:relative;}'."\n";
			$mediaquerystyle .='	#bpg-container{position:absolute; top:auto; bottom:5%;}'."\n";
			$mediaquerystyle .='	#main-footer-container{position:relative; bottom:auto;}'."\n";
			$mediaquerystyle .='	#primary{height:auto;} .toslide{display:none;}'."\n";
			$mediaquerystyle .='	.slimScrollDiv, .entry-content{max-height:100%; height:auto !important;}'."\n";
			$mediaquerystyle .='}'."\n";
			$mediaquerystyle .='@media (max-width: 979px) {'."\n";
			$mediaquerystyle .='	body{font-size:12px;}'."\n";
			$mediaquerystyle .='	.large, h1{font-size:1.333em; margin-bottom:1em;}'."\n";
			$mediaquerystyle .='	.medium, h2{font-size:1.167em; margin-bottom:0.5em;}'."\n";
			$mediaquerystyle .='	.normal, h3 {font-size:1.083em; margin-bottom:0.5em;}'."\n";	
			$mediaquerystyle .='	.normal, h4, h5, h6{font-size:1em;}'."\n";
			$mediaquerystyle .='	.content{width:718px;}'."\n";
			$mediaquerystyle .='	#cta-container .cta{width:auto;}'."\n";
			$mediaquerystyle .='	#header{height:auto; position:relative;}'."\n";
			$mediaquerystyle .='	#google-translate-container{float:none; position:relative;}'."\n";
			$mediaquerystyle .='	#logo-container{display:block; position:relative; text-align:center;}'."\n";
			$mediaquerystyle .='	#slider-container{min-height:0;}'."\n";
			$mediaquerystyle .='	#secondary-menu-container{float:none; margin-bottom:1em;}'."\n";
			$mediaquerystyle .='	#secondary-menu ul{text-align:center;}'."\n";
			$mediaquerystyle .='	#social-media-container{float:none; text-align:center;}'."\n";
			$mediaquerystyle .='	#footer{height:auto;}'."\n";
			$mediaquerystyle .='}'."\n";
			$mediaquerystyle .='@media(max-width:800px) {'."\n";
			$mediaquerystyle .='	#header-container{padding-top:30px !important;}'."\n";
			$mediaquerystyle .='	#main-menu-container{position:fixed; top:0; width:100%;}'."\n";
			$mediaquerystyle .='	#cta-container{position: absolute; width: auto; height: auto; bottom: -260px; left:5%;}'."\n";
			$mediaquerystyle .='	#cta-container .cta{padding:1em;}'."\n";
			$mediaquerystyle .='	#cta-container .control-wrapper{display:block; position:relative; width:auto; margin:0 0 1em;;}'."\n";	
			$mediaquerystyle .='}'."\n";
			$mediaquerystyle .='@media (max-width: 767px) {'."\n";
			$mediaquerystyle .='	.content{width:auto;}'."\n";
			$mediaquerystyle .='	#header{position:relative;}'."\n";
			$mediaquerystyle .='	#main-menu{background:#d6d6d6; display:block; position:relative; width:100%; margin:0 auto; bottom:0;}'."\n";
			$mediaquerystyle .='		#main-menu ul li{display:block; position:relative; text-align:center; margin:0;}'."\n";
			$mediaquerystyle .='	.image-container{width:300px; margin:0 auto 1em;}'."\n";
			$mediaquerystyle .='	.visible-layer{display:none;}'."\n";
			$mediaquerystyle .='	.hide-layer{display:block;}'."\n";
			$mediaquerystyle .='}'."\n";
			$mediaquerystyle .='@media (max-width:570px) {'."\n";
			$mediaquerystyle .='	#cta-container{position:relative; bottom:auto; left:auto;}'."\n";
			$mediaquerystyle .='	#cta-container .cta{display:block; position:relative; margin:0 auto; text-align:center; width:240px;}'."\n";
			$mediaquerystyle .='	.flex-control-nav {display:none;}'."\n";
			$mediaquerystyle .='	.image-container{width:auto; margin:0 auto 1em;}'."\n";
			$mediaquerystyle .='	#bpgmodal h2{font-size:1.231em;}'."\n";
			$mediaquerystyle .='	.bpgtip #bpgtipcontent{top:150%; left:0; min-height:140px; width:100%;}'."\n";
			$mediaquerystyle .='	#bpgtipcontent:after{border-color:transparent transparent #E0C48F transparent; left:45%; top:-24px;}'."\n";
			$mediaquerystyle .='}'."\n";
			$mediaquerystyle .='@media (max-width: 480px) {'."\n";
			$mediaquerystyle .='}'."\n";
			return $mediaquerystyle;
		} break;
		case 'style3' : {
			$mediaquerystyle .= '@media (min-width: 1367px) {'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width:1366px) {'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media(max-width:1199px) {'."\n";
			$mediaquerystyle .= '	.content{width:960px;}'."\n";
			$mediaquerystyle .= '	#main-menu > ul li a{padding:8px 12px;}'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width: 979px) {'."\n";
			$mediaquerystyle .= '	.content{width:auto; padding:0 1em;}'."\n";
			$mediaquerystyle .= '	#header{position:relative; top:auto;}'."\n";
			$mediaquerystyle .= '	#slider-main{font-size:12px;}'."\n";
			$mediaquerystyle .= '	#slider-main .slider-image-caption{top:auto; bottom:0; width:100%; left:0;}'."\n";
			$mediaquerystyle .= '	#slider-carousel{display:none;}'."\n";
			$mediaquerystyle .= '	#main-menu ul li{display:block; position:relative; text-align:center; margin:0;}'."\n";
			$mediaquerystyle .= '	#main-menu ul li a{margin:0; color:#fff; background:#252525;}'."\n";
			$mediaquerystyle .= '	#main-menu ul li a:hover, #main-menu ul li.current-menu-item a{border:none;}'."\n";
			$mediaquerystyle .= '	.image-container{width:300px; margin:0 auto 1em;}'."\n";
			$mediaquerystyle .= '	.visible-layer{display:none;}'."\n";
			$mediaquerystyle .= '	.hide-layer{display:block;}'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width: 767px) {'."\n";
			$mediaquerystyle .= '	.content{width:500px; padding:0;}'."\n";
			$mediaquerystyle .= '	.image-container{width:300px; margin:0 auto 1em;}'."\n";
			$mediaquerystyle .= '	#teaser-container .image-container{width:auto;}'."\n";
			$mediaquerystyle .= '	#footer .content, #header .content{width:auto;}'."\n";
			$mediaquerystyle .= '	#header .content{padding:0;}'."\n";
			$mediaquerystyle .= '	#footer .content{padding:0 1em;}'."\n";
			$mediaquerystyle .= '	#menu-container{position:relative;}'."\n";
			$mediaquerystyle .= '	#main-menu{background:#b3b2b2; display:block; position:relative; width:100%; margin:0 auto; bottom:0;}'."\n";
			$mediaquerystyle .= '	#slider-container{margin:0 0 1em;}'."\n";
			$mediaquerystyle .= '	#primary, #sidebar{width:auto; border:none; padding:0; margin:0 0 1em; float:none;}'."\n";
			$mediaquerystyle .= '	#social-media-container{float:none; text-align:left;}'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width:570px) {'."\n";
			$mediaquerystyle .= '	body{font-size:12px;}'."\n";
			$mediaquerystyle .= '	.content{width:320px;}'."\n";
			$mediaquerystyle .= '	.image-container{width:auto;}'."\n";
			$mediaquerystyle .= '	#footer-logo-container, #logo-container{width:300px; margin:0 auto;}'."\n";
			$mediaquerystyle .= '		#footer-logo-container img, #logo-container img{width:100%;}'."\n";
			$mediaquerystyle .= '	#slider-main .slider-image-caption{display:none; }'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width: 480px) {'."\n";
			$mediaquerystyle .= '	.content{width:280px;}'."\n";
			$mediaquerystyle .= '	#logo-container{width:280px; margin:0 auto;}'."\n";
			$mediaquerystyle .= '		#logo-container img{width:100%;}'."\n";
			$mediaquerystyle .= '}'."\n";
			return $mediaquerystyle;
		} break;
		case 'style4' : {
			$mediaquerystyle .= '@media (min-width: 1367px) {'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width:1366px) {'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media(max-width:1199px) {'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width: 979px) {'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width: 767px) {'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width:570px) {'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width: 480px) {'."\n";
			$mediaquerystyle .= '}'."\n";
			return $mediaquerystyle;
		} break;
		default : {
			$mediaquerystyle  = '@media (min-width: 1367px) {'."\n";
			$mediaquerystyle .= '	.content{width:1100px;}'."\n";
			$mediaquerystyle .= '	#slider-container{max-width:1960px; margin:0 auto;}'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width:1366px) {'."\n";
			$mediaquerystyle .= '	.content{width:1100px;}'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media(max-width:1199px) {'."\n";
			$mediaquerystyle .= '	.content{width:960px;}'."\n";
			$mediaquerystyle .= '	.bpgtip{left:0;}'."\n";
			$mediaquerystyle .= '	#bpgtipcontent{top:200%; left:-15px; height:auto; min-width:200px; font-size:12px;}'."\n";
			$mediaquerystyle .= '	#bpgtipcontent:after{top:-24px; border-color: transparent transparent #E0C48F transparent; }'."\n";
			$mediaquerystyle .= '	#bpgmodal h2{font-size:1.231em;}'."\n";
			$mediaquerystyle .= '	#cta-container{width:250px; text-align:center; bottom:10%; right:10%; padding:10px;}'."\n";
			$mediaquerystyle .= '	#cta-container .content{width:auto;}'."\n";
			$mediaquerystyle .= '	#cta-container .control-wrapper{display:block; position:relative; margin-bottom:0.5em;}'."\n";
			$mediaquerystyle .= '	#cta-container .cta-moc-container{width:auto;}'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width: 979px) {'."\n";
			$mediaquerystyle .= '	body{font-size:12px;}'."\n";
			$mediaquerystyle .= '	.large, h1{font-size:1.333em; margin-bottom:1em;}'."\n";
			$mediaquerystyle .= '	.medium, h2{font-size:1.167em; margin-bottom:0.5em;}'."\n";
			$mediaquerystyle .= '	.normal, h3 {font-size:1.083em; margin-bottom:0.5em;}'."\n";	
			$mediaquerystyle .= '	.normal, h4, h5, h6{font-size:1em;}'."\n";
			$mediaquerystyle .= '	.content{width:718px;}'."\n";
			$mediaquerystyle .= '	#header{height:auto; position:relative;}'."\n";
			$mediaquerystyle .= '	#logo-container{display:block; position:relative; text-align:center;}'."\n";
			$mediaquerystyle .= '	#main-menu-container{position:relative; bottom:auto; right:auto;}'."\n";
			$mediaquerystyle .= '	#slider-container{min-height:0;}'."\n";
			$mediaquerystyle .= '	#secondary-menu-container{float:none; margin-bottom:1em;}'."\n";
			$mediaquerystyle .= '	#secondary-menu ul{text-align:center;}'."\n";
			$mediaquerystyle .= '	#social-media-container{float:none; text-align:center;}'."\n";
			$mediaquerystyle .= '	#footer{height:auto;}'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width: 767px) {'."\n";
			$mediaquerystyle .= '	.content{width:500px;}'."\n";
			$mediaquerystyle .= '	#header{position:relative;}'."\n";
			$mediaquerystyle .= '	#footer .content, #header .content{width:auto;}'."\n";
			$mediaquerystyle .= '	#main-menu{background:#d6d6d6; display:block; position:relative; width:100%; margin:0 auto; bottom:0;}'."\n";
			$mediaquerystyle .= '		#main-menu ul li{display:block; position:relative; text-align:center; margin:0;}'."\n";
			$mediaquerystyle .= '	.image-container{width:300px; margin:0 auto 1em;}'."\n";
			$mediaquerystyle .= '	.visible-layer{display:none;}'."\n";
			$mediaquerystyle .= '	.hide-layer{display:block;}'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width:570px) {'."\n";
			$mediaquerystyle .= '	#cta-container{width: auto; padding:10px; position:relative; right:auto; bottom:auto;}'."\n";
			$mediaquerystyle .= '	.flex-control-nav {display:none;}'."\n";
			$mediaquerystyle .= '	.content{width:320px;}'."\n";
			$mediaquerystyle .= '	.image-container{width:auto; margin:0 auto 1em;}'."\n";
			$mediaquerystyle .= '}'."\n";
			$mediaquerystyle .= '@media (max-width: 480px) {'."\n";
			$mediaquerystyle .= '	.content{width:280px;}'."\n";
			$mediaquerystyle .= '}'."\n";
			return $mediaquerystyle;
		}
	}

}

?>